<?php
/**
 * Slack.com Integration
 *
 * PHP Version 5
 *
 * @category  Steverobbins
 * @package   Steverobbins_Slack
 * @author    Steve Robbins <steve@steverobbins.com>
 * @copyright Copyright 2015 Steve Robbins (http://steverobbins.com)
 * @license   http://creativecommons.org/licenses/by/3.0/deed.en_US Creative Commons Attribution 3.0 Unported License
 */

/**
 * @var $this Steverobbins_Slack_Block_Adminhtml_System_Config_Channels_List
 */

$_channels = $this->getChannels();
?>
<?php if (is_array($_channels) && count($_channels)): ?>
<div class="grid">
    <table cellpadding="0" cellspacing="0" class="border">
        <thead>
            <tr class="headings">
                <th><?php echo $this->__('Identifier') ?></th>
                <th><?php echo $this->__('Name') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->getChannels() as $_id => $_name): ?>
            <tr>
                <td><?php echo $_id ?></td>
                <td><?php echo $_name ?></td>
            </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div>
<?php endif ?>
